import { buildSchema } from "./schema";
import { CanvasGraph, RelationSchema, Schema } from "./types";

interface RelationInfo {
  relatedTable: string;
  localColumn: string;
  remoteColumn: string;
  isIncoming: boolean;
}

function buildRelationMap(schema: Schema): Map<string, RelationInfo[]> {
  const map = new Map<string, RelationInfo[]>();
  const push = (table: string, info: RelationInfo) => {
    const arr = map.get(table) ?? [];
    arr.push(info);
    map.set(table, arr);
  };
  for (const rel of schema.relations as RelationSchema[]) {
    push(rel.toTable, {
      relatedTable: rel.fromTable,
      localColumn: rel.toColumn,
      remoteColumn: rel.fromColumn,
      isIncoming: true,
    });
    push(rel.fromTable, {
      relatedTable: rel.toTable,
      localColumn: rel.fromColumn,
      remoteColumn: rel.toColumn,
      isIncoming: false,
    });
  }
  return map;
}

function toPascalCase(s: string): string {
  return s
    .split(/[_\- ]+/)
    .filter(Boolean)
    .map((w) => w[0]!.toUpperCase() + w.slice(1).toLowerCase())
    .join("");
}

function isAutoIncrement(t: string): boolean {
  const x = t.toLowerCase();
  return x === "serial" || x === "bigserial" || x === "smallserial";
}

function isTimestamp(name: string, type: string): boolean {
  const t = type.toLowerCase();
  const n = name.toLowerCase();
  return t.includes("timestamp") || n.includes("created_at") || n.includes("updated_at");
}

function sqlToPrismaType(sqlType: string): string {
  const t = (sqlType ?? "").trim().toLowerCase();
  if (t === "uuid") return "String";
  if (t.startsWith("varchar") || t === "text" || t.startsWith("char")) return "String";
  if (t === "integer" || t === "int" || t === "int4") return "Int";
  if (t === "bigint" || t === "int8") return "BigInt";
  if (t === "smallint" || t === "int2") return "Int";
  if (t === "boolean" || t === "bool") return "Boolean";
  if (t.startsWith("decimal") || t.startsWith("numeric")) return "Decimal";
  if (t === "float" || t === "real" || t === "float4") return "Float";
  if (t === "double precision" || t === "float8") return "Float";
  if (t === "timestamp" || t.startsWith("timestamp")) return "DateTime";
  if (t === "date" || t === "time") return "DateTime";
  if (t === "json" || t === "jsonb") return "Json";
  if (t === "bytea") return "Bytes";
  return "String";
}

export function generatePrisma(jsonData: Buffer | string | CanvasGraph): string {
  const schema = buildSchema(jsonData);
  const out: string[] = [
    "// Generated by Skyforge\n",
    'generator client {\n  provider = "prisma-client-js"\n}\n',
    'datasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n',
  ];

  const relMap = buildRelationMap(schema);

  for (const table of schema.tables) {
    const modelName = toPascalCase(table.name);
    const lines: string[] = [`model ${modelName} {`];

    for (const col of table.columns) {
      const prismaType = sqlToPrismaType(col.type);
      const attrs: string[] = [];
      if (col.isPrimary) {
        attrs.push("@id");
        if (col.type.toLowerCase() === "uuid") attrs.push("@default(uuid())");
        else if (isAutoIncrement(col.type)) attrs.push("@default(autoincrement())");
      }
      if (col.isUnique && !col.isPrimary) attrs.push("@unique");
      if (isTimestamp(col.name, col.type)) {
        const lower = col.name.toLowerCase();
        if (lower.includes("created")) attrs.push("@default(now())");
        else if (lower.includes("updated")) attrs.push("@updatedAt");
      }

      const optional = !col.notNull && !col.isPrimary ? "?" : "";
      const attrStr = attrs.length ? ` ${attrs.join(" ")}` : "";
      lines.push(`  ${col.name} ${prismaType}${optional}${attrStr}`);
    }

    const rels = relMap.get(table.name) ?? [];
    for (const rel of rels) {
      const relModel = toPascalCase(rel.relatedTable);
      if (rel.isIncoming) {
        let fieldName = rel.localColumn.replace(/_id$/, "");
        if (fieldName === rel.localColumn) fieldName = rel.relatedTable;
        lines.push(
          `  ${fieldName} ${relModel} @relation(fields: [${rel.localColumn}], references: [${rel.remoteColumn}])`,
        );
      } else {
        lines.push(`  ${rel.relatedTable}s ${relModel}[]`);
      }
    }

    lines.push("}\n");
    out.push(lines.join("\n"));
  }

  return out.join("\n");
}
