import { buildSchema, cleanName, fallbackType, findColumn } from "./schema";
import { CanvasGraph } from "./types";

export function generateSQL(jsonData: Buffer | string | CanvasGraph): string {
  const schema = buildSchema(jsonData);
  const out: string[] = ["-- Generated by Skyforge\n"];

  for (const table of schema.tables) {
    const tableName = cleanName(table.name);
    out.push(`CREATE TABLE ${tableName} (`);

    const pkCols: string[] = [];
    table.columns.forEach((col, i) => {
      const colName = cleanName(col.name);
      const colType = fallbackType(col.type);
      let line = `  ${colName} ${colType}`;
      if (col.notNull || col.isPrimary) line += " NOT NULL";
      if (col.isUnique && !col.isPrimary) line += " UNIQUE";
      if (col.isPrimary) pkCols.push(colName);
      const isLast = i === table.columns.length - 1 && pkCols.length === 0;
      if (!isLast) line += ",";
      out.push(line);
    });

    if (pkCols.length > 0) out.push(`  PRIMARY KEY (${pkCols.join(", ")})`);
    out.push(");\n");
  }

  const seenIndexes = new Set<string>();
  for (const rel of schema.relations) {
    const constraint = `fk_${cleanName(rel.toTable)}_${cleanName(rel.fromTable)}_${cleanName(rel.fromColumn)}`;
    out.push(
      `ALTER TABLE ${cleanName(rel.toTable)}\n  ADD CONSTRAINT ${constraint}\n  FOREIGN KEY (${cleanName(rel.toColumn)}) REFERENCES ${cleanName(rel.fromTable)}(${cleanName(rel.fromColumn)});\n`,
    );

    const target = findColumn(schema.tables, rel.toTable, rel.toColumn);
    if (target && !target.isPrimary) {
      const idxName = `idx_${cleanName(rel.toTable)}_${cleanName(rel.toColumn)}_fk`;
      if (!seenIndexes.has(idxName)) {
        out.push(`CREATE INDEX ${idxName} ON ${cleanName(rel.toTable)} (${cleanName(rel.toColumn)});\n`);
        seenIndexes.add(idxName);
      }
    }
  }

  return out.join("\n") + "\n";
}
