import { GoogleGenerativeAI } from "@google/generative-ai";

const SYSTEM_TABLES_PROMPT = `You are a database schema designer. Based on the user's description, generate a database schema with tables and their relationships.

IMPORTANT: Return ONLY valid JSON, no markdown, no backticks, no explanations.

The JSON must follow this exact structure:
{
  "tables": [
    {
      "name": "table_name_in_snake_case",
      "columns": [
        {
          "name": "column_name",
          "type": "uuid|varchar(255)|text|integer|bigint|boolean|timestamp|date|decimal(10,2)|jsonb",
          "isPrimaryKey": true/false,
          "constraints": ["NN"]
        }
      ]
    }
  ],
  "relations": [
    {
      "fromTable": "child_table",
      "fromColumn": "foreign_key_column",
      "toTable": "parent_table",
      "toColumn": "primary_key_column"
    }
  ]
}

Rules:
1. Every table MUST have an "id" column with type "uuid" as primary key
2. Use snake_case for all table and column names
3. Include created_at (timestamp) and updated_at (timestamp) columns for most tables
4. Use appropriate data types: uuid for IDs, varchar(255) for short strings, text for long content, integer for counts, boolean for flags, timestamp for dates
5. Add "NN" (NOT NULL) constraint to required fields
6. For foreign keys, name them as: referenced_table_id (e.g., user_id references users.id)
7. Create sensible relationships between tables based on the user's description
8. Return ONLY the JSON object, nothing else`;

const SYSTEM_SQL_PROMPT = `You are an expert PostgreSQL database architect. Given a database schema in JSON format, generate production-ready PostgreSQL DDL (Data Definition Language).

IMPORTANT: Return ONLY the SQL code, no markdown, no backticks, no explanations.

Requirements:
1. Generate CREATE TABLE statements with proper column definitions
2. Use appropriate PostgreSQL data types
3. Add PRIMARY KEY constraints inline or as table constraints
4. Add NOT NULL constraints where specified (columns with "NN" in constraints)
5. Add UNIQUE constraints where appropriate
6. Generate ALTER TABLE statements for FOREIGN KEY constraints based on the edges (relationships)
7. Create indexes on foreign key columns for better query performance
8. Use snake_case for all identifiers
9. Add appropriate DEFAULT values:
   - uuid columns: DEFAULT gen_random_uuid()
   - serial/bigserial: auto-increment (no explicit default needed)
   - created_at: DEFAULT CURRENT_TIMESTAMP
   - updated_at: DEFAULT CURRENT_TIMESTAMP
10. Order tables so that referenced tables are created before tables that reference them
11. Add a header comment: -- Generated by Skyforge AI
12. Group related statements together with comments

Edge format explanation:
- "source" is the table ID containing the foreign key
- "target" is the table ID being referenced
- "sourceHandle" contains the column ID of the foreign key (format: "columnId-source")
- "targetHandle" contains the column ID being referenced (format: "columnId-target")

Generate clean, well-formatted, production-ready SQL.`;

const SYSTEM_PRISMA_PROMPT = `You are an expert Prisma schema designer. Given a database schema in JSON format, generate a production-ready Prisma schema file.

IMPORTANT: Return ONLY the Prisma schema code, no markdown, no backticks, no explanations.

Requirements:
1. Start with the standard generator and datasource blocks:
   generator client {
     provider = "prisma-client-js"
   }

   datasource db {
     provider = "postgresql"
     url      = env("DATABASE_URL")
   }

2. Generate model definitions for each table (node)
3. Use PascalCase for model names (convert snake_case table names)
4. Use camelCase for field names where appropriate, but keep snake_case for database column names using @map
5. Map Prisma types correctly:
   - uuid -> String @id @default(uuid())
   - serial/bigserial -> Int @id @default(autoincrement())
   - varchar/text -> String
   - integer/int -> Int
   - bigint -> BigInt
   - boolean -> Boolean
   - timestamp/timestamptz -> DateTime
   - date -> DateTime
   - decimal -> Decimal
   - float/double precision -> Float
   - json/jsonb -> Json
   - bytea -> Bytes

6. Add appropriate attributes:
   - @id for primary keys
   - @unique for unique constraints
   - @default() with appropriate values
   - @updatedAt for updated_at columns
   - @map() for column name mapping if needed
   - @@map() for table name mapping if needed

7. Generate relation fields based on edges:
   - Add relation fields on both sides of the relationship
   - Use @relation directive with fields and references
   - Name relation fields appropriately (singular for belongsTo, plural for hasMany)

8. Add a header comment: // Generated by Skyforge AI

Edge format explanation:
- "source" is the table ID containing the foreign key
- "target" is the table ID being referenced
- "sourceHandle" contains the column ID of the foreign key (format: "columnId-source")
- "targetHandle" contains the column ID being referenced (format: "columnId-target")

Generate clean, well-formatted, production-ready Prisma schema.`;

export function aiAvailable(): boolean {
  return !!process.env.GEMINI_API_KEY;
}

function getModel() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error("GEMINI_API_KEY is not set");
  const client = new GoogleGenerativeAI(apiKey);
  return client.getGenerativeModel({ model: "gemini-2.0-flash" });
}

function stripFences(s: string): string {
  return s
    .trim()
    .replace(/^```(?:json|sql|postgresql|prisma)?/i, "")
    .replace(/```$/i, "")
    .trim();
}

function generateId(): string {
  const chars = "abcdefghijklmnopqrstuvwxyz0123456789";
  let r = "";
  for (let i = 0; i < 9; i++) r += chars[Math.floor(Math.random() * chars.length)];
  return `id_${Date.now() * 1000}_${r}`;
}

interface AITable {
  name: string;
  columns: Array<{
    name: string;
    type: string;
    isPrimaryKey: boolean;
    constraints: string[];
  }>;
}

interface AIRelation {
  fromTable: string;
  fromColumn: string;
  toTable: string;
  toColumn: string;
}

interface AIResponse {
  tables: AITable[];
  relations: AIRelation[];
}

export async function generateTablesFromPrompt(prompt: string) {
  const model = getModel();
  const fullPrompt = `${SYSTEM_TABLES_PROMPT}\n\nUser request: ${prompt}`;
  const result = await model.generateContent(fullPrompt);
  const text = stripFences(result.response.text());

  let parsed: AIResponse;
  try {
    parsed = JSON.parse(text) as AIResponse;
  } catch (err) {
    throw new Error(`failed to parse AI response: ${(err as Error).message}`);
  }
  if (!parsed.tables?.length) throw new Error("AI did not generate any tables");

  const tableNodeMap: Record<string, string> = {};
  const columnIdMap: Record<string, Record<string, string>> = {};

  const nodes = parsed.tables.map((table, i) => {
    const nodeId = generateId();
    tableNodeMap[table.name] = nodeId;
    columnIdMap[nodeId] = {};
    const x = (i % 3) * 350 + 100;
    const y = Math.floor(i / 3) * 400 + 100;
    const columns = table.columns.map((col) => {
      const colId = generateId();
      columnIdMap[nodeId]![col.name] = colId;
      return {
        id: colId,
        name: col.name,
        type: col.type,
        isPrimaryKey: col.isPrimaryKey,
        constraints: col.constraints,
      };
    });
    return {
      id: nodeId,
      type: "tableNode",
      position: { x, y },
      data: { name: table.name, columns },
    };
  });

  const edges: unknown[] = [];
  for (const rel of parsed.relations ?? []) {
    const sourceNode = tableNodeMap[rel.fromTable];
    const targetNode = tableNodeMap[rel.toTable];
    if (!sourceNode || !targetNode) continue;
    const sourceCol = columnIdMap[sourceNode]?.[rel.fromColumn];
    const targetCol = columnIdMap[targetNode]?.[rel.toColumn];
    if (!sourceCol || !targetCol) continue;
    edges.push({
      id: generateId(),
      source: sourceNode,
      target: targetNode,
      sourceHandle: `${sourceCol}-source`,
      targetHandle: `${targetCol}-target`,
      type: "smoothstep",
      animated: true,
    });
  }

  return { nodes, edges };
}

export async function generateSQLFromCanvas(canvasJSON: string): Promise<string> {
  const model = getModel();
  const result = await model.generateContent(`${SYSTEM_SQL_PROMPT}\n\nCanvas Schema JSON:\n${canvasJSON}`);
  return stripFences(result.response.text());
}

export async function generatePrismaFromCanvas(canvasJSON: string): Promise<string> {
  const model = getModel();
  const result = await model.generateContent(`${SYSTEM_PRISMA_PROMPT}\n\nCanvas Schema JSON:\n${canvasJSON}`);
  return stripFences(result.response.text());
}
