// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: database_connections.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createDatabaseConnection = `-- name: CreateDatabaseConnection :one
INSERT INTO database_connections (
    user_id, project_id, name, host, port, database_name, username, password, db_type, ssl_mode
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, name, host, port, database_name, username, password, db_type, ssl_mode, created_at, updated_at, project_id
`

type CreateDatabaseConnectionParams struct {
	UserID       uuid.UUID     `json:"user_id"`
	ProjectID    uuid.NullUUID `json:"project_id"`
	Name         string        `json:"name"`
	Host         string        `json:"host"`
	Port         int32         `json:"port"`
	DatabaseName string        `json:"database_name"`
	Username     string        `json:"username"`
	Password     string        `json:"password"`
	DbType       string        `json:"db_type"`
	SslMode      string        `json:"ssl_mode"`
}

func (q *Queries) CreateDatabaseConnection(ctx context.Context, arg CreateDatabaseConnectionParams) (DatabaseConnection, error) {
	row := q.db.QueryRowContext(ctx, createDatabaseConnection,
		arg.UserID,
		arg.ProjectID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.DatabaseName,
		arg.Username,
		arg.Password,
		arg.DbType,
		arg.SslMode,
	)
	var i DatabaseConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.Password,
		&i.DbType,
		&i.SslMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
	)
	return i, err
}

const deleteDatabaseConnection = `-- name: DeleteDatabaseConnection :exec
DELETE FROM database_connections
WHERE id = $1 AND user_id = $2
`

type DeleteDatabaseConnectionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDatabaseConnection(ctx context.Context, arg DeleteDatabaseConnectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteDatabaseConnection, arg.ID, arg.UserID)
	return err
}

const getDatabaseConnectionByID = `-- name: GetDatabaseConnectionByID :one
SELECT id, user_id, name, host, port, database_name, username, password, db_type, ssl_mode, created_at, updated_at, project_id FROM database_connections
WHERE id = $1 AND user_id = $2
`

type GetDatabaseConnectionByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetDatabaseConnectionByID(ctx context.Context, arg GetDatabaseConnectionByIDParams) (DatabaseConnection, error) {
	row := q.db.QueryRowContext(ctx, getDatabaseConnectionByID, arg.ID, arg.UserID)
	var i DatabaseConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.Password,
		&i.DbType,
		&i.SslMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
	)
	return i, err
}

const getDatabaseConnectionByProjectID = `-- name: GetDatabaseConnectionByProjectID :one
SELECT id, user_id, name, host, port, database_name, username, password, db_type, ssl_mode, created_at, updated_at, project_id FROM database_connections
WHERE project_id = $1 AND user_id = $2
`

type GetDatabaseConnectionByProjectIDParams struct {
	ProjectID uuid.NullUUID `json:"project_id"`
	UserID    uuid.UUID     `json:"user_id"`
}

func (q *Queries) GetDatabaseConnectionByProjectID(ctx context.Context, arg GetDatabaseConnectionByProjectIDParams) (DatabaseConnection, error) {
	row := q.db.QueryRowContext(ctx, getDatabaseConnectionByProjectID, arg.ProjectID, arg.UserID)
	var i DatabaseConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.Password,
		&i.DbType,
		&i.SslMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
	)
	return i, err
}

const getDatabaseConnectionsByUser = `-- name: GetDatabaseConnectionsByUser :many
SELECT id, user_id, name, host, port, database_name, username, password, db_type, ssl_mode, created_at, updated_at, project_id FROM database_connections
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetDatabaseConnectionsByUser(ctx context.Context, userID uuid.UUID) ([]DatabaseConnection, error) {
	rows, err := q.db.QueryContext(ctx, getDatabaseConnectionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DatabaseConnection
	for rows.Next() {
		var i DatabaseConnection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.DatabaseName,
			&i.Username,
			&i.Password,
			&i.DbType,
			&i.SslMode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const testDatabaseConnection = `-- name: TestDatabaseConnection :one
SELECT id, name, host, port, database_name, username, db_type, ssl_mode
FROM database_connections
WHERE id = $1 AND user_id = $2
`

type TestDatabaseConnectionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type TestDatabaseConnectionRow struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Host         string    `json:"host"`
	Port         int32     `json:"port"`
	DatabaseName string    `json:"database_name"`
	Username     string    `json:"username"`
	DbType       string    `json:"db_type"`
	SslMode      string    `json:"ssl_mode"`
}

func (q *Queries) TestDatabaseConnection(ctx context.Context, arg TestDatabaseConnectionParams) (TestDatabaseConnectionRow, error) {
	row := q.db.QueryRowContext(ctx, testDatabaseConnection, arg.ID, arg.UserID)
	var i TestDatabaseConnectionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.DbType,
		&i.SslMode,
	)
	return i, err
}

const updateDatabaseConnection = `-- name: UpdateDatabaseConnection :one
UPDATE database_connections
SET project_id = $3,
    name = $4,
    host = $5,
    port = $6,
    database_name = $7,
    username = $8,
    password = $9,
    db_type = $10,
    ssl_mode = $11,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, host, port, database_name, username, password, db_type, ssl_mode, created_at, updated_at, project_id
`

type UpdateDatabaseConnectionParams struct {
	ID           uuid.UUID     `json:"id"`
	UserID       uuid.UUID     `json:"user_id"`
	ProjectID    uuid.NullUUID `json:"project_id"`
	Name         string        `json:"name"`
	Host         string        `json:"host"`
	Port         int32         `json:"port"`
	DatabaseName string        `json:"database_name"`
	Username     string        `json:"username"`
	Password     string        `json:"password"`
	DbType       string        `json:"db_type"`
	SslMode      string        `json:"ssl_mode"`
}

func (q *Queries) UpdateDatabaseConnection(ctx context.Context, arg UpdateDatabaseConnectionParams) (DatabaseConnection, error) {
	row := q.db.QueryRowContext(ctx, updateDatabaseConnection,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.DatabaseName,
		arg.Username,
		arg.Password,
		arg.DbType,
		arg.SslMode,
	)
	var i DatabaseConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.Password,
		&i.DbType,
		&i.SslMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
	)
	return i, err
}
