// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Project struct {
	ID          uuid.UUID       `json:"id"`
	UserID      uuid.UUID       `json:"user_id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	Data        json.RawMessage `json:"data"`
	IsPublic    bool            `json:"is_public"`
	LastSavedAt time.Time       `json:"last_saved_at"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type ProjectCollaborator struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type ProjectShareLink struct {
	ID         uuid.UUID    `json:"id"`
	ProjectID  uuid.UUID    `json:"project_id"`
	Token      string       `json:"token"`
	RoomKey    string       `json:"room_key"`
	CreatedBy  uuid.UUID    `json:"created_by"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
	CreatedAt  time.Time    `json:"created_at"`
	LastUsedAt sql.NullTime `json:"last_used_at"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	Email     string         `json:"email"`
	Name      string         `json:"name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	Provider  string         `json:"provider"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type DatabaseConnection struct {
	ID           uuid.UUID     `json:"id"`
	UserID       uuid.UUID     `json:"user_id"`
	ProjectID    uuid.NullUUID `json:"project_id"`
	Name         string        `json:"name"`
	Host         string        `json:"host"`
	Port         int32         `json:"port"`
	DatabaseName string        `json:"database_name"`
	Username     string        `json:"username"`
	Password     string        `json:"password"`
	DbType       string        `json:"db_type"`
	SslMode      string        `json:"ssl_mode"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
}
