// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_share_links.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProjectShareLink = `-- name: CreateProjectShareLink :one
INSERT INTO project_share_links (project_id, token, room_key, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, token, room_key, created_by, expires_at, revoked_at, created_at, last_used_at
`

type CreateProjectShareLinkParams struct {
	ProjectID uuid.UUID    `json:"project_id"`
	Token     string       `json:"token"`
	RoomKey   string       `json:"room_key"`
	CreatedBy uuid.UUID    `json:"created_by"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) CreateProjectShareLink(ctx context.Context, arg CreateProjectShareLinkParams) (ProjectShareLink, error) {
	row := q.db.QueryRowContext(ctx, createProjectShareLink,
		arg.ProjectID,
		arg.Token,
		arg.RoomKey,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i ProjectShareLink
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Token,
		&i.RoomKey,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getActiveShareLinkForProject = `-- name: GetActiveShareLinkForProject :one
SELECT id, project_id, token, room_key, created_by, expires_at, revoked_at, created_at, last_used_at
FROM project_share_links
WHERE project_id = $1
  AND revoked_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveShareLinkForProject(ctx context.Context, projectID uuid.UUID) (ProjectShareLink, error) {
	row := q.db.QueryRowContext(ctx, getActiveShareLinkForProject, projectID)
	var i ProjectShareLink
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Token,
		&i.RoomKey,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getShareLinkByToken = `-- name: GetShareLinkByToken :one
SELECT id, project_id, token, room_key, created_by, expires_at, revoked_at, created_at, last_used_at
FROM project_share_links
WHERE token = $1
  AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetShareLinkByToken(ctx context.Context, token string) (ProjectShareLink, error) {
	row := q.db.QueryRowContext(ctx, getShareLinkByToken, token)
	var i ProjectShareLink
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Token,
		&i.RoomKey,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const revokeShareLinksForProject = `-- name: RevokeShareLinksForProject :exec
UPDATE project_share_links
SET revoked_at = NOW()
WHERE project_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeShareLinksForProject(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeShareLinksForProject, projectID)
	return err
}
